from __future__ import annotations

import json
import logging
from typing import Any

from django.conf import settings

logger = logging.getLogger(__name__)

STATIC_FALLBACK = (
    "The session shows measurable cart abandonment risk. Review the dominant S1-S7 reason, "
    "remove the strongest checkout barrier, and validate the change with a small A/B test."
)


def generate_recommendation(scores: dict, session_context: dict) -> str:
    """Generate a short recommendation via Gemini, with a deterministic fallback."""

    dominant = session_context.get("dominant_reason") or scores.get("dominant_key") or "S1"
    api_key = getattr(settings, "GEMINI_API_KEY", "") or ""
    if not api_key:
        return f"{STATIC_FALLBACK} Dominant reason: {dominant}."

    try:
        from google import genai

        client = genai.Client(api_key=api_key)
        prompt = (
            "You are advising an ecommerce owner. "
            f"Scores: {scores}. Context: {session_context}. "
            "Write 2-3 concise, practical recommendations in English."
        )
        resp = client.models.generate_content(model="gemini-1.5-flash", contents=prompt)
        text = getattr(resp, "text", None) or str(resp)
        return text.strip() if text.strip() else f"{STATIC_FALLBACK} Dominant reason: {dominant}."
    except Exception as exc:
        logger.error("Gemini API error: %s", exc)
        return f"{STATIC_FALLBACK} Dominant reason: {dominant}."


def fallback_structured_recommendation(
    *,
    dominant_reason: str,
    reason_label: str,
    scores: dict[str, float],
    probability: float,
    top_features: list[dict[str, Any]] | None = None,
    events: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    evidence = [
        f"Dominant reason is {dominant_reason} ({reason_label}).",
        f"Abandonment probability is {probability:.2f}.",
    ]
    for item in (top_features or [])[:2]:
        feature = item.get("feature")
        if feature:
            evidence.append(f"Important model signal: {feature}.")
    if events:
        evidence.append(f"Event timeline contains {len(events)} tracked events.")

    return {
        "title": f"Fix {reason_label.lower()}",
        "summary": (
            f"The session is most strongly explained by {dominant_reason} - {reason_label}. "
            "Review the evidence, remove the strongest visible barrier, and measure conversion rate after the change."
        ),
        "reason_code": dominant_reason,
        "priority": "high" if probability >= 0.75 else "medium" if probability >= 0.5 else "low",
        "effort": "medium",
        "expected_impact": "Lower cart abandonment and improve checkout conversion.",
        "evidence": evidence,
        "action_steps": [
            "Inspect the checkout/cart step related to the dominant reason.",
            "Make one focused UX or messaging change.",
            "Compare abandonment rate before and after the change.",
        ],
        "warning": "Generated by fallback rule because Gemini API is not configured or did not return valid JSON.",
        "source": "fallback",
    }


def generate_structured_recommendation(
    *,
    dominant_reason: str,
    reason_label: str,
    scores: dict[str, float],
    probability: float,
    top_features: list[dict[str, Any]] | None = None,
    events: list[dict[str, Any]] | None = None,
    cart_summary: dict[str, Any] | None = None,
    device_info: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Return recommendation JSON for dashboard cards. Falls back deterministically."""

    fallback = fallback_structured_recommendation(
        dominant_reason=dominant_reason,
        reason_label=reason_label,
        scores=scores,
        probability=probability,
        top_features=top_features,
        events=events,
    )
    api_key = getattr(settings, "GEMINI_API_KEY", "") or ""
    if not api_key:
        return fallback

    try:
        from google import genai

        client = genai.Client(api_key=api_key)
        prompt = f"""
You are an ecommerce conversion analyst.

Generate a practical recommendation for a shop owner based only on the provided session diagnosis.
Do not invent data. If evidence is insufficient, say that evidence is insufficient.
Return business-friendly Mongolian text. Return valid JSON only.

Input:
- dominant_reason: {dominant_reason}
- reason_label: {reason_label}
- S1-S7 scores: {scores}
- abandonment_probability: {probability}
- top_features: {top_features or []}
- event_timeline: {events or []}
- cart_summary: {cart_summary or {}}
- device_info: {device_info or {}}

Return schema:
{{
  "title": "short recommendation title",
  "summary": "one paragraph explanation",
  "reason_code": "S1|S2|S3|S4|S5|S6|S7",
  "priority": "low|medium|high",
  "effort": "low|medium|high",
  "expected_impact": "what KPI may improve",
  "evidence": ["evidence point 1", "evidence point 2"],
  "action_steps": ["step 1", "step 2", "step 3"],
  "warning": "limitation or empty string"
}}
""".strip()
        resp = client.models.generate_content(model="gemini-1.5-flash", contents=prompt)
        text = (getattr(resp, "text", None) or str(resp)).strip()
        parsed = json.loads(text)
        if not isinstance(parsed, dict):
            return fallback
        parsed["source"] = "gemini"
        parsed.setdefault("reason_code", dominant_reason)
        parsed.setdefault("warning", "")
        return parsed
    except Exception as exc:
        logger.error("Gemini structured recommendation error: %s", exc)
        return fallback
