import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    borderRadius: {
      none: "0px",
      sm: "0.375rem",
      DEFAULT: "0.5rem",
      md: "0.625rem",
      lg: "0.75rem",
      xl: "1rem",
      "2xl": "1.25rem",
      "3xl": "1.5rem",
      full: "9999px",
    },
    extend: {
      fontFamily: {
        display: ["var(--font-display)", "Newsreader", "Noto Sans Mongolian", "serif"],
        headline: ["Newsreader", "Noto Sans Mongolian", "serif"],
        body: ["var(--font-body)", "Work Sans", "Noto Sans Mongolian", "sans-serif"],
        label: ["var(--font-body)", "Work Sans", "Noto Sans Mongolian", "sans-serif"],
      },
      boxShadow: {
        card: "0 1px 2px rgb(15 23 42 / 0.04), 0 10px 28px -8px rgb(15 23 42 / 0.12)",
        "card-dark": "0 1px 2px rgb(0 0 0 / 0.25), 0 12px 30px -10px rgb(0 0 0 / 0.5)",
      },
      colors: {
        "surface-dim": "rgb(var(--surface-dim-rgb) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--secondary-fixed-dim-rgb) / <alpha-value>)",
        "surface-variant": "rgb(var(--surface-variant-rgb) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--on-secondary-fixed-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--surface-container-high-rgb) / <alpha-value>)",
        "on-primary-container": "rgb(var(--on-primary-container-rgb) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--on-secondary-container-rgb) / <alpha-value>)",
        outline: "rgb(var(--outline-rgb) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--on-primary-fixed-rgb) / <alpha-value>)",
        "on-primary": "rgb(var(--on-primary-rgb) / <alpha-value>)",
        "primary-dim": "rgb(var(--primary-dim-rgb) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--on-primary-fixed-variant-rgb) / <alpha-value>)",
        surface: "rgb(var(--surface-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--on-surface-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant-rgb) / <alpha-value>)",
        "primary-fixed": "rgb(var(--primary-fixed-rgb) / <alpha-value>)",
        "on-error": "rgb(var(--on-error-rgb) / <alpha-value>)",
        background: "rgb(var(--background-rgb) / <alpha-value>)",
        "surface-bright": "rgb(var(--surface-bright-rgb) / <alpha-value>)",
        "inverse-surface": "rgb(var(--inverse-surface-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--surface-container-lowest-rgb) / <alpha-value>)",
        "tertiary-container": "rgb(var(--tertiary-container-rgb) / <alpha-value>)",
        "surface-tint": "rgb(var(--surface-tint-rgb) / <alpha-value>)",
        "inverse-primary": "rgb(var(--inverse-primary-rgb) / <alpha-value>)",
        "primary-container": "rgb(var(--primary-container-rgb) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--on-tertiary-fixed-variant-rgb) / <alpha-value>)",
        "on-error-container": "rgb(var(--on-error-container-rgb) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--tertiary-fixed-dim-rgb) / <alpha-value>)",
        "on-tertiary": "rgb(var(--on-tertiary-rgb) / <alpha-value>)",
        "on-secondary": "rgb(var(--on-secondary-rgb) / <alpha-value>)",
        "secondary-dim": "rgb(var(--secondary-dim-rgb) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--inverse-on-surface-rgb) / <alpha-value>)",
        tertiary: "rgb(var(--tertiary-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--surface-container-low-rgb) / <alpha-value>)",
        "secondary-container": "rgb(var(--secondary-container-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant-rgb) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--on-secondary-fixed-variant-rgb) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--surface-container-highest-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--on-background-rgb) / <alpha-value>)",
        secondary: "rgb(var(--secondary-rgb) / <alpha-value>)",
        primary: "rgb(var(--primary-rgb) / <alpha-value>)",
        error: "rgb(var(--error-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--surface-container-rgb) / <alpha-value>)",
        "error-container": "rgb(var(--error-container-rgb) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--tertiary-fixed-rgb) / <alpha-value>)",
        "error-dim": "rgb(var(--error-dim-rgb) / <alpha-value>)",
        "tertiary-dim": "rgb(var(--tertiary-dim-rgb) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--primary-fixed-dim-rgb) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--on-tertiary-container-rgb) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--on-tertiary-fixed-rgb) / <alpha-value>)",
        insight: "rgb(var(--insight-bg-rgb) / <alpha-value>)",
        "on-insight": "rgb(var(--on-insight-rgb) / <alpha-value>)",
        canvas: "rgb(var(--canvas-rgb) / <alpha-value>)",
        "surface-alt": "rgb(var(--surface-alt-rgb) / <alpha-value>)",
      },
    },
  },
  plugins: [],
};

export default config;
