"""
Django settings for main_service project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
import warnings
from datetime import timedelta
from importlib.util import find_spec
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'change-me-insecure-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() == 'true'

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'apps.accounts',
    'apps.tenants',
    'apps.analytics',
    'apps.diagnosis',
]

if find_spec('django_prometheus'):
    INSTALLED_APPS.insert(0, 'django_prometheus')

MIDDLEWARE = [
    *(['django_prometheus.middleware.PrometheusBeforeMiddleware'] if find_spec('django_prometheus') else []),
    'corsheaders.middleware.CorsMiddleware',  # MUST be first
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    *(['django_prometheus.middleware.PrometheusAfterMiddleware'] if find_spec('django_prometheus') else []),
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
]
_frontend_url = os.getenv("FRONTEND_URL", "")
if _frontend_url:
    CORS_ALLOWED_ORIGINS.append(_frontend_url)

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",
]

ROOT_URLCONF = 'main_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


def _postgres_db_config(prefix: str) -> dict | None:
    db_host = os.getenv(f'{prefix}_HOST', '').strip()
    if not db_host:
        return None
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv(f'{prefix}_NAME', 'main_service'),
        'USER': os.getenv(f'{prefix}_USER', 'postgres'),
        'PASSWORD': os.getenv(f'{prefix}_PASSWORD', ''),
        'HOST': db_host,
        'PORT': os.getenv(f'{prefix}_PORT', '5432'),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
    }


def _database_from_url(url_env: str) -> dict | None:
    """
    Optional DATABASE_URL-style configuration for the main service DB.
    """
    import dj_database_url

    raw = os.getenv(url_env, '').strip()
    if not raw:
        return None
    return dj_database_url.parse(raw, conn_max_age=600, ssl_require=False)


# Database (default + observer alias)
default_db_from_url = _database_from_url('DATABASE_URL')
if default_db_from_url:
    DATABASES = {'default': default_db_from_url}
else:
    default_pg = _postgres_db_config('DB')
    if default_pg:
        DATABASES = {'default': default_pg}
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

DATABASES['default'].setdefault('TEST', {'MIRROR': None})

observer_pg = _postgres_db_config('OBSERVER_DB')
if observer_pg:
    observer_pg['OPTIONS'] = {'options': '-c default_transaction_read_only=on'}
    observer_pg.setdefault('TEST', {'MIRROR': None})
    DATABASES['observer'] = observer_pg
elif not (len(sys.argv) > 1 and sys.argv[1] == 'test'):
    # Dev fallback: read tasks run against the default DB (no read-only flag to avoid breaking writes).
    DATABASES['observer'] = {
        **DATABASES['default'],
        'TEST': {'MIRROR': 'default'},
    }

DATABASE_ROUTERS = ['apps.analytics.db_router.ObserverMigrationGuardRouter']

# DRF authentication/permission defaults (JWT)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '300/minute',
    },
    'EXCEPTION_HANDLER': 'main_service.exceptions.custom_exception_handler',
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery / Redis
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379')
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f'{REDIS_URL}/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f'{REDIS_URL}/1')
CELERY_TIMEZONE = TIME_ZONE
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_RESULT_EXPIRES = int(os.getenv('CELERY_TASK_RESULT_EXPIRES', '3600'))
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.getenv('CELERY_MAX_TASKS_PER_CHILD', '1000'))

try:
    from celery.schedules import crontab
except ImportError:
    crontab = None

CELERY_BEAT_SCHEDULE = {
    # Existing Redis/DB workflows for diagnosis.
    'poll_unprocessed_sessions-every-30s': {
        'task': 'apps.diagnosis.tasks.poll_unprocessed_sessions',
        'schedule': 30.0,
    },
    'consume_diagnosis_queue-once-every-2s': {
        'task': 'apps.analytics.tasks.consume_ca_diagnosis_queue_once',
        'schedule': 2.0,
    },
    'export_predictions_daily': {
        'task': 'apps.analytics.tasks.export_to_minio',
        'schedule': crontab(hour=1, minute=0) if crontab else 3600.0,
        'kwargs': {'export_type': 'analytics'},
    },
}

# DuckDB analytics storage (single file)
DUCKDB_PATH = os.getenv('DUCKDB_PATH', '')
if not DUCKDB_PATH:
    DUCKDB_PATH = str(BASE_DIR / 'analytics.duckdb')
    warnings.warn(
        'DUCKDB_PATH not set; using a local project file. Mount a persistent volume in production.',
        stacklevel=1,
    )

# MinIO / S3 export
MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT', '')
MINIO_BUCKET = os.getenv('MINIO_BUCKET', '')
MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY', '')
MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY', '')
MINIO_USE_SSL = os.getenv('MINIO_USE_SSL', 'false').lower() == 'true'

# Gemini API
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Kafka
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")

# JWT logout support (token blacklist).
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
}

# Email
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@cartanalytics.mn")

_json_formatter = (
    {
        '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
        'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
    }
    if find_spec('pythonjsonlogger')
    else {'format': '%(asctime)s %(levelname)s %(name)s %(message)s'}
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': _json_formatter,
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {'handlers': ['console'], 'level': os.getenv('LOG_LEVEL', 'INFO')},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'celery': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}
