# Generated by Django 5.1.6 on 2026-03-25 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=128)),
                ("visitor_id", models.CharField(db_index=True, max_length=128)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("smart", "Smart"),
                            ("full", "Full"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score_s1", models.DecimalField(decimal_places=4, max_digits=6)),
                ("score_s2", models.DecimalField(decimal_places=4, max_digits=6)),
                ("score_s3", models.DecimalField(decimal_places=4, max_digits=6)),
                ("score_s4", models.DecimalField(decimal_places=4, max_digits=6)),
                ("score_s5", models.DecimalField(decimal_places=4, max_digits=6)),
                ("score_s6", models.DecimalField(decimal_places=4, max_digits=6)),
                ("score_s7", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Created"), ("failed", "Failed")],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observer_session_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("visitor_id", models.CharField(db_index=True, max_length=128)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("smart", "Smart"),
                            ("full", "Full"),
                        ],
                        max_length=10,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_sessions",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_mn", models.TextField()),
                ("dominant_score", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("viewed", "Viewed"),
                            ("implemented", "Implemented"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="analytics.diagnosis",
                    ),
                ),
                (
                    "implemented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implemented_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="diagnosis",
            constraint=models.UniqueConstraint(
                fields=("tenant", "session_id"), name="unique_diagnosis_tenant_session"
            ),
        ),
    ]
