# Generated by Django 5.1.6 on 2026-04-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_session_event_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="predictionresult",
            new_name="analytics_p_tenant__ca658b_idx",
            old_name="analytics_p_tenant__3ae95e_idx",
        ),
        migrations.RenameIndex(
            model_name="session",
            new_name="analytics_s_tenant__19f172_idx",
            old_name="analytics_s_tenant__c4c0da_idx",
        ),
        migrations.RenameIndex(
            model_name="session",
            new_name="analytics_s_tenant__02c3ad_idx",
            old_name="analytics_s_tenant__b1c803_idx",
        ),
        migrations.RenameIndex(
            model_name="visitoroutcome",
            new_name="analytics_v_actual__6eb488_idx",
            old_name="analytics_v_actual__ab_idx",
        ),
    ]
