# Generated by Django 5.1.6 on 2026-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0009_predictionresult_feature_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("viewed", "Viewed"),
                    ("in_progress", "In Progress"),
                    ("implemented", "Implemented"),
                    ("dismissed", "Dismissed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
